name: daily_logger
description: Daily logger app.

version: 1.0.0+0

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2

  # network, dunno for what
  # http: any
  # DI
  provider: ^4.1.3
  get_it: ^3.1.0
  # db
  hive: ^1.4.1+1
  hive_flutter: ^0.3.0+2
  # misc
  universal_platform: ^0.1.3
  intl: ^0.16.1
  scrollable_positioned_list: ^0.1.2
  google_fonts: ^0.3.10

# dev_dependencies:
  # flutter_test:
  #   sdk: flutter

  # hive_generator: ^0.7.0+2
  # build_runner: ^1.10.0

flutter:
  uses-material-design: true
  fonts:
    - family: VT323
      fonts:
        - asset: assets/fonts/VT323/VT323-Regular.ttf
    - family: Nova Mono
      fonts:
        - asset: assets/fonts/Nova_Mono/NovaMono-Regular.ttf
    - family: Fira Code
      fonts:
        - asset: assets/fonts/Fira_Code/FiraCode-Regular.ttf
        - asset: assets/fonts/Fira_Code/FiraCode-Medium.ttf
          weight: 400
        - asset: assets/fonts/Fira_Code/FiraCode-Bold.ttf
          weight: 700
        - asset: assets/fonts/Fira_Code/FiraCode-Light.ttf
          weight: 200
        - asset: assets/fonts/Fira_Code/FiraCode-SemiBold.ttf
          weight: 600
